import { expect, it } from "@effect/vitest";
import {
  CommandId,
  HERMES_DRIVER_KIND,
  MessageId,
  ProjectId,
  ProviderInstanceId,
  ThreadId,
  type OrchestrationV2Command,
} from "@t3tools/contracts";
import * as Effect from "effect/Effect";

import { SqlitePersistenceMemory } from "../persistence/Layers/Sqlite.ts";
import { legacyAdapterV2Capabilities } from "./Adapters/LegacyAdapterV2.ts";
import { OrchestratorV2 } from "./Orchestrator.ts";
import type { ProviderAdapterV2Shape } from "./ProviderAdapter.ts";
import * as ProviderAdapterRegistry from "./ProviderAdapterRegistry.ts";
import { makeOrchestratorV2ReplayLayerWithRegistry } from "./testkit/ProviderReplayHarness.ts";

const instanceId = ProviderInstanceId.make("hermes-notifications");
const adapter: ProviderAdapterV2Shape = {
  instanceId,
  driver: HERMES_DRIVER_KIND,
  getCapabilities: () =>
    Effect.succeed(
      legacyAdapterV2Capabilities(
        {
          resume: "acp",
          nativeHistory: false,
          reasoning: true,
          approvals: true,
          questions: true,
          mcp: true,
        },
        true,
      ),
    ),
  planSelectionTransition: () => Effect.succeed({ type: "apply_on_next_turn" }),
  openSession: () => Effect.die("A proactive delivery must not start a provider session"),
};
const testLayer = makeOrchestratorV2ReplayLayerWithRegistry(
  { name: "hermes-notifications" },
  ProviderAdapterRegistry.makeLayer([adapter]),
  { databaseLayer: SqlitePersistenceMemory, runEffectWorker: false },
);

it.effect("keeps an ownership race retryable and commits proactive output exactly once", () =>
  Effect.gen(function* () {
    const orchestrator = yield* OrchestratorV2;
    const threadId = ThreadId.make("thread:hermes-notifications");
    yield* orchestrator.dispatch({
      type: "thread.create",
      commandId: CommandId.make("create-hermes-notifications"),
      threadId,
      projectId: ProjectId.make("project:hermes-notifications"),
      title: "Home",
      modelSelection: { instanceId, model: "hermes" },
      runtimeMode: "full-access",
      interactionMode: "default",
      branch: null,
      worktreePath: null,
      createdBy: "agent",
      creationSource: "server",
    });
    const command: Extract<OrchestrationV2Command, { type: "thread.notification.deliver" }> = {
      type: "thread.notification.deliver",
      commandId: CommandId.make("hermes-racing-delivery"),
      threadId,
      expectedProviderInstanceId: instanceId,
      messageId: MessageId.make("hermes-message"),
      deliveryId: "gateway-delivery",
      kind: "cron",
      label: "Daily report",
      text: "Already generated by Hermes",
      createdAt: "2026-09-22T12:00:00.000Z",
    };
    const rejected = yield* orchestrator
      .dispatch({
        ...command,
        expectedProviderInstanceId: ProviderInstanceId.make("old-owner"),
      })
      .pipe(Effect.result);
    expect(rejected._tag).toBe("Failure");

    const committed = yield* orchestrator.dispatch(command);
    const repeated = yield* orchestrator.dispatch({ ...command, text: "Changed retry" });
    expect(repeated.sequence).toBe(committed.sequence);
    const projection = yield* orchestrator.getThreadProjection(threadId);
    expect(projection.runs).toEqual([]);
    expect(projection.providerSessions).toEqual([]);
    expect(projection.messages).toHaveLength(1);
    expect(projection.turnItems).toHaveLength(1);
    expect(projection.messages[0]?.text).toBe("> Daily report\n\nAlready generated by Hermes");
  }).pipe(Effect.provide(testLayer)),
);
